// Generated by scripts/build-notes.py from notes/*.md.
window.BLOG_NOTES = [
  {
    "title": "Effective C++ 读书笔记",
    "summary": "整理《Effective C++》中的语言基础、资源管理、接口设计与继承实践，保留旧博客原有笔记与代码示例。",
    "tags": [
      "C++",
      "Effective C++",
      "最佳实践"
    ],
    "date": "2025-11-20",
    "category": "读书笔记",
    "url": "./reading/effective-cpp.html",
    "markdown": "./notes/effective-cpp.md"
  }
];
